`timescale 1ns / 1ps

/**
 * @param a first 1-bit input
 * @param b second 1-bit input
 * @param g whether a and b generate a carry
 * @param p whether a and b would propagate an incoming carry
 */
module gp1(input wire a, b,
           output wire g, p);
   assign g = a & b;
   assign p = a | b;
endmodule

/**
 * Computes aggregate generate/propagate signals over a 4-bit window.
 * @param gin incoming generate signals
 * @param pin incoming propagate signals
 * @param cin the incoming carry
 * @param gout whether these 4 bits internally would generate a carry-out (independent of cin)
 * @param pout whether these 4 bits internally would propagate an incoming carry from cin
 * @param cout the carry outs for the low-order 3 bits
 */
module gp4(input wire [3:0] gin, pin,
           input wire cin,
           output wire gout, pout,
           output wire [2:0] cout);

   // TODO: your code here
   assign cout[0] = gin[0] | (pin[0] & cin);
   wire g10 = (gin[0] & pin[1]) | gin[1];
   assign cout[1] = (cin & pin[0] & pin[1]) | g10;
   assign cout[2] = gin[2] | (pin[2] & g10) | (pin[2] & pin[1] & pin[0] & cin);
   assign pout = pin[0] & pin[1] & pin[2] & pin[3];
   wire g32 = (gin[2] & pin[3]) | gin[3];
   assign gout = g32 | (g10 & pin[3] & pin[2]);

endmodule

/** Same as gp4 but for an 8-bit window instead */
module gp8(input wire [7:0] gin, pin,
           input wire cin,
           output wire gout, pout,
           output wire [6:0] cout);

   // TODO: your code here
   wire g30, p30, g74, p74;
   wire [2:0] c31;
   wire [2:0] c74;
   // calculate G3-0, P3-0, and C1, C2, C3
   gp4 lower(.gin(gin[3:0]), .pin(pin[3:0]), .cin(cin), .gout(g30), .pout(p30), .cout(c31));
   assign cout[3] = g30 | (p30 & cin);
   // calculate G7-4, P7-4, and C5, C6, C7
   gp4 upper(.gin(gin[7:4]), .pin(pin[7:4]), .cin(g30 | (p30 & cin)), .gout(g74), .pout(p74), .cout(c74));
   assign cout[0] = c31[0];
   assign cout[1] = c31[1];
   assign cout[2] = c31[2];

   assign cout[4] = c74[0];
   assign cout[5] = c74[1];
   // G7-0 is either generated by G7-4 or propagated from G3-0 through P7-4
   assign gout = (p74 & g30) | g74;

   assign pout = p30 & p74;
   assign cout[6] = c74[2];
endmodule

module CarryLookaheadAdder
  (input wire [31:0]  a, b,
   input wire         cin,
   output wire [31:0] sum);

   // TODO: your code here
   wire [31:0] g;
   wire [31:0] p;
   wire [31:0] c;
   // Generate g and p signals for each bit
   genvar i;
   generate 
      for (i = 0; i < 32; i++) begin : gp_gen
         gp1 gp_inst(.a(a[i]), .b(b[i]), .g(g[i]), .p(p[i]));
   end 
   wire g70, g158, g2316, g3124;
   wire p70, p158, p2316, p3124;
   assign c[0] = cin;
   // Calculate G7-0, P7-0, and C1 to C7
   gp8 lower8(.gin(g[7:0]), .pin(p[7:0]), .cin(cin), .gout(g70), .pout(p70), .cout(c[7:1]));
   assign c[8] = g70 | (p70 & cin);
   // Calculate G15-8, P15-8, and C9 to C15
   gp8 midlower8(.gin(g[15:8]), .pin(p[15:8]), .cin(g70 | (p70 & cin)), .gout(g158), .pout(p158), .cout(c[15:9]));
   assign c[16] = g158 | (p158 & (g70 | (p70 & cin)));
   // Calculate G23-16, P23-16, and C17 to C23
   gp8 midupper8(.gin(g[23:16]), .pin(p[23:16]), .cin(g158 | (p158 & (g70 | (p70 & cin)))), .gout(g2316), .pout(p2316), .cout(c[23:17]));
   assign c[24] = g2316 | (p2316 & (g158 | (p158 & (g70 | (p70 & cin)))));
   // Calculate G31-24, P31-24, and C25 to C31
   gp8 upper8(.gin(g[31:24]), .pin(p[31:24]), .cin(g2316 | (p2316 & (g158 | (p158 & (g70 | (p70 & cin)))))), .gout(g3124), .pout(p3124), .cout(c[31:25]));
   // Calculate sum bits
   for (i = 0; i < 32; i++) begin : sum_gen
      assign sum[i] = a[i] ^ b[i] ^ c[i];
   end

   endgenerate

endmodule
